#!/usr/bin/env bash
# Freeze the FastAPI backend into a standalone binary with PyInstaller.
#
# Run from the repo root:
#   source .venv/bin/activate
#   ./scripts/build_backend_binary.sh
#
# Output: dist/backend/nexzam-backend/ (onedir bundle), which
# src-tauri/tauri.conf.json's bundle.resources maps into the packaged app.

set -euo pipefail

cd "$(dirname "$0")/.."

# Bake the version being frozen so the running binary can report it. A frozen
# backend has no repo to read tauri.conf.json from.
VERSION="$(python3 -c 'import json;print(json.load(open("src-tauri/tauri.conf.json"))["version"])')"
cat > app/backend/_baked_version.py <<EOF
# Generated by scripts/build_backend_binary.sh -- do not edit.
BAKED_VERSION = "$VERSION"
EOF
echo "Baking backend version $VERSION"

pyinstaller --name nexzam-backend --onedir --noconfirm \
  --distpath dist/backend --workpath build/backend --specpath build \
  --paths . \
  --hidden-import uvicorn.logging \
  --hidden-import uvicorn.lifespan.on \
  --hidden-import uvicorn.protocols.http.h11_impl \
  --hidden-import multipart \
  --hidden-import multipart.multipart \
  app/backend/bundle_entrypoint.py

rm -f app/backend/_baked_version.py
echo "Wrote dist/backend/nexzam-backend/ (version $VERSION)"
